version: "3.8"

services:
  # Redis Service
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
